---
- name: LANG | Ensure the locale exists
  locale_gen:
    name: "{{ system_locale }}"
    state: present

- name: LANG | Set as default locale
  template:
    src: locale.conf.j2
    dest: /etc/locale.conf
