---

- name: SERVICES | Enable NetworkManager
  service: name=NetworkManager state=started enabled=true

- name: SERVICES | Enable sddm
  service: name=sddm state=started enabled=true
  when: de == "plasma"
