---

- name: GRUB | Truncate old cfg
  copy:
    content: ""
    dest: "/etc/default/grub"
    force: yes

- name: GRUB | Write new cfg
  blockinfile:
    path: "/etc/default/grub"
    insertafter: '#New grub configuration'
    block: |
      GRUB_TIMEOUT=5
      GRUB_DISTRIBUTOR="Arch"
      GRUB_CMDLINE_LINUX_DEFAULT="loglevel=3 quiet splash root=/dev/nvme0n1p3 resume=/dev/nvme0n1p2"
      GRUB_CMDLINE_LINUX=""
      GRUB_PRELOAD_MODULES="part_gpt part_msdos"
      GRUB_TIMEOUT_STYLE=menu
      GRUB_TERMINAL_INPUT=console
      GRUB_GFXMODE=auto
      GRUB_GFXPAYLOAD_LINUX=keep
      GRUB_DISABLE_LINUX_UUID=true
      GRUB_DISABLE_RECOVERY=true

- name: Grub install
  command: grub-install --target=x86_64-efi --efi-directory=/boot/efi --bootloader-id=GRUB

- name: Grub mkconfig
  command: grub-mkconfig -o /boot/grub/grub.cfg