- name: Modify pacman.conf
  blockinfile:
    path: /etc/pacman.conf
    insertafter: "# enable the multilib repositories are required here."
    block: |
       [multilib]
       Include = /etc/pacman.d/mirrorlist
