- name: Modify pacman.conf
  lineinfile:
    insertafter: '# enable the multilib repositories are required here.'
    path: /etc/pacman.conf
    line: "{{ item }}"
  with_items:
    - "[multilib]"
    - "Include = /etc/pacman.d/mirrorlist"
